version: '25.0.3'

services:
  database:
    image: mysql
    container_name: MB-Server
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'api'
    ports:
      - '3306:3306'
